// <auto-generated />
using CPRG214.Assets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPRG214.Assets.Data.Migrations
{
    [DbContext(typeof(AssetContext))]
    partial class AssetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CPRG214.Assets.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Asset");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Description = "Dell Computer",
                            Manufacturer = "Dell",
                            Model = "Inspiron",
                            SerialNumber = "525ABCC",
                            TagNumber = "1A425C"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            Description = "HP Computer",
                            Manufacturer = "HP",
                            Model = "Pavilion",
                            SerialNumber = "2745ABC",
                            TagNumber = "2A435C"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 1,
                            Description = "Acer Computer",
                            Manufacturer = "Acer",
                            Model = "SF314",
                            SerialNumber = "12B657C",
                            TagNumber = "2B572C"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 2,
                            Description = "Acer Monitor",
                            Manufacturer = "Acer",
                            Model = "Nitro",
                            SerialNumber = "22MF625",
                            TagNumber = "1B552M"
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 2,
                            Description = "LG Monitor",
                            Manufacturer = "LG",
                            Model = "IPS",
                            SerialNumber = "25M62J75",
                            TagNumber = "22C52M"
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 2,
                            Description = "HP Monitor",
                            Manufacturer = "HP",
                            Model = "Ultraslim",
                            SerialNumber = "65MFL525",
                            TagNumber = "1R252M"
                        },
                        new
                        {
                            Id = 7,
                            AssetTypeId = 3,
                            Description = "Avaya Phone",
                            Manufacturer = "Avaya",
                            Model = "9612G",
                            SerialNumber = "55P6F665",
                            TagNumber = "G25687P"
                        },
                        new
                        {
                            Id = 8,
                            AssetTypeId = 3,
                            Description = "Polycom Phone",
                            Manufacturer = "Polycom",
                            Model = "VVX155",
                            SerialNumber = "35P86BK487",
                            TagNumber = "9FC687P"
                        },
                        new
                        {
                            Id = 9,
                            AssetTypeId = 3,
                            Description = "Cisco Phone",
                            Manufacturer = "Cisco",
                            Model = "VoIP",
                            SerialNumber = "25P86CF665",
                            TagNumber = "2CY687P"
                        });
                });

            modelBuilder.Entity("CPRG214.Assets.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Computer Monitor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("CPRG214.Assets.Domain.Asset", b =>
                {
                    b.HasOne("CPRG214.Assets.Domain.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    //b.Navigation("AssetType");
                });

            modelBuilder.Entity("CPRG214.Assets.Domain.AssetType", b =>
                {
                    //b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
